# Generated by Django 4.1.3 on 2022-11-14 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название вида спорта')),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('address', models.CharField(max_length=30, verbose_name='Адрес')),
                ('capacity', models.IntegerField(verbose_name='Вместимость')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название команды')),
                ('city', models.CharField(max_length=30, verbose_name='Город')),
                ('players_quantity', models.IntegerField(verbose_name='Количество игроков')),
                ('coach', models.CharField(max_length=30, verbose_name='Тренер')),
            ],
        ),
        migrations.CreateModel(
            name='Sportsman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=30, verbose_name='Отчество')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessor.team', verbose_name='Команда')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата выступления')),
                ('attempt_number', models.IntegerField(verbose_name='Номер попытки')),
                ('attempt_result', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Результат попытки')),
                ('sportsman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessor.sportsman', verbose_name='Спортсмен')),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessor.sporttype', verbose_name='Спорт')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessor.stadium', verbose_name='Стадион')),
            ],
        ),
    ]
