# Generated by Django 4.1.3 on 2022-11-14 22:54

import random
from django.db import migrations
from accessor.models import Team, Sportsman


def fill_sportsman(apps, schema_editor):

    teams = Team.objects.all()

    first_names = [
        'Александр', 'Аникей', 'Василий', 'Владимир', 'Глеб', 'Захар', 'Кузьма', 'Никита',
        'Николай', 'Максим', 'Михаил', 'Олег', 'Павел', 'Тимур', 'Тихон', 'Ярослав'
             ]

    middle_names = [
        'Александрович', 'Аникеевич', 'Васильевич', 'Владимирович', 'Глебович', 'Захарович' 'Никитович',
        'Николаевич', 'Максимович', 'Михайлович', 'Олегович', 'Павлович', 'Тимурович', 'Тихонович', 'Ярославович'
             ]

    last_names = [
        'Павлов', 'Козлов', 'Степанов', 'Николаев', 'Орлов', 'Андреев', 'Макаров', 'Никитин', 'Захаров',
        'Зайцев', 'Соловьев', 'Борисов', 'Яковлев', 'Григорьев', 'Романов', 'Воробьев'
    ]

    for team in teams:
        for players_quantity in range(team.players_quantity):
            Sportsman.objects.create(first_name=random.choice(first_names), middle_name=random.choice(middle_names),
                                     last_name=random.choice(last_names), team=team)


class Migration(migrations.Migration):

    dependencies = [
        ('accessor', '0002_auto_20221115_0125'),
    ]

    operations = [
        migrations.RunPython(fill_sportsman)
    ]
