# Generated by Django 4.1.3 on 2022-11-15 16:18

import random
import time

from django.db import migrations
from accessor.models import Sportsman, Result


def fill_result(apps, schema_editor):

    sportsmen = Sportsman.objects.all()

    for sportsman in sportsmen:
        time_format = "%Y-%m-%d"
        start_date = time.mktime(time.strptime("2022-5-1", time_format))
        end_date = time.mktime(time.strptime("2022-5-30", time_format))
        random_number = random.random()
        random_date = start_date + random_number * (end_date - start_date)
        date = time.strftime(time_format, time.localtime(random_date))

        Result.objects.create(date=date, attempt_number=random.randint(1, 10),
                              attempt_result=random.randint(0, 10), sportsman=sportsman)


class Migration(migrations.Migration):

    dependencies = [
        ('accessor', '0003_auto_20221115_0154'),
    ]

    operations = [
        migrations.RunPython(fill_result)
    ]
