# Generated by Django 4.1.3 on 2022-11-15 20:28

import random
from django.db import migrations

from django.db import migrations
from accessor.models import Sportsman, Result


def fill_sport(apps, schema_editor):

    sport = apps.get_model('accessor', 'SportType')

    names = [
        'Волейбол', 'Хоккей', 'Прыжки на батуте', 'Гимнастика', 'Стрельба из лука',
        'Баскетбол', 'Фехтование', 'Альпинизм', 'Тяжёлая атлетика', 'Регби', 'Борьба', 'Гольф'
    ]

    for name in names:
        sport.objects.create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('accessor', '0004_auto_20221115_1918'),
    ]

    operations = [
        migrations.RunPython(fill_sport)
    ]
