# Generated by Django 4.1.3 on 2022-11-15 20:39

from django.db import migrations


def fill_stadium(apps, schema_editor):

    stadium = apps.get_model('accessor', 'Stadium')

    names = [
        'Лужники', 'Газпром Арена', 'Ак Барс Арена', 'Открытие Банк Арена', 'Волгоград Арена',
        'Нижний Новгород', 'Солидарность Самара Арена', 'Ростов Арена',
        'Мордовия арена', 'Фишт', 'Краснодар', 'Калининград'
    ]

    addresses = [
        'Москва', 'Санкт-Петербург', 'Казань', 'Моква', 'Волгоград',
        'Нижний Новгород', 'Самара', 'Ростов-на-Дону', 'Саранск',
        'Сочи', 'Краснодар', 'Калининград'
    ]

    capacities = [
        81000, 63026, 45379, 45360, 45015, 45000, 45000, 43300, 42839, 41220, 35179, 35015
    ]

    for index in range(len(names)):
        stadium.objects.create(name=names[index],
                               address=addresses[index], capacity=capacities[index])


class Migration(migrations.Migration):

    dependencies = [
        ('accessor', '0005_auto_20221115_2328'),
    ]

    operations = [
        migrations.RunPython(fill_stadium)
    ]
